version: '3'
services:
  api:
    build: ./reflanx/flask_app
    depends_on:
      - db
    env_file: ./reflanx/flask_app/.env
    environment:
      - APP_DATABASE=postgresql://postgres@db/postgres
      - CELERY_BACKEND=redis://redis
      - CELERY_BROKER=redis://redis
      - DATA_WAREHOUSE_DATABASE=postgresql://postgres@data_warehouse/postgres
      - PROJECT_HOME=/app
  celery:
    build:
      context: ./reflanx/flask_app
      dockerfile: Dockerfile-celery
    depends_on:
      - redis
    env_file: ./reflanx/flask_app/.env
    environment:
      - APP_DATABASE=postgresql://postgres@db/postgres
      - CELERY_BACKEND=redis://redis
      - CELERY_BROKER=redis://redis
      - DATA_WAREHOUSE_DATABASE=postgresql://postgres@data_warehouse/postgres
      - PROJECT_HOME=/app
  data_warehouse:
    image: postgres
  db:
    image: postgres
  redis:
    image: redis
  web:
    build: ./reflanx/react_app
    depends_on:
      - api
    ports:
      - ${PORT:-8001}:80

    